name: al_mehdi_online_school
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  iconsax_flutter: ^1.0.0
  pie_chart: ^5.4.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  file_picker: ^10.1.9
  google_sign_in: ^6.3.0
  firebase_core_web: ^2.23.0
  firebase_auth_web: ^5.14.3
  google_sign_in_web: ^0.12.4+4
  flutter_web_auth_2: ^4.1.0
  provider: ^6.1.5
  image_picker: ^1.1.2
  auto_size_text: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/
    - assets/fonts/
    - assets/logo/

  fonts:
   - family: Roboto
     fonts:
       - asset: assets/fonts/static/Roboto-Black.ttf
       - asset: assets/fonts/static/Roboto-BlackItalic.ttf
       - asset: assets/fonts/static/Roboto-Bold.ttf
       - asset: assets/fonts/static/Roboto-BoldItalic.ttf
       - asset: assets/fonts/static/Roboto-ExtraBold.ttf
       - asset: assets/fonts/static/Roboto-ExtraBoldItalic.ttf
       - asset: assets/fonts/static/Roboto-ExtraLight.ttf
       - asset: assets/fonts/static/Roboto-ExtraLightItalic.ttf
       - asset: assets/fonts/static/Roboto-Italic.ttf
       - asset: assets/fonts/static/Roboto-Light.ttf
       - asset: assets/fonts/static/Roboto-LightItalic.ttf
       - asset: assets/fonts/static/Roboto-Medium.ttf
       - asset: assets/fonts/static/Roboto-MediumItalic.ttf
       - asset: assets/fonts/static/Roboto-Regular.ttf
       - asset: assets/fonts/static/Roboto-SemiBold.ttf
       - asset: assets/fonts/static/Roboto-SemiBoldItalic.ttf
       - asset: assets/fonts/static/Roboto-Thin.ttf
       - asset: assets/fonts/static/Roboto-ThinItalic.ttf
       - asset: assets/fonts/static/Roboto-ThinItalic.ttf
