// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy5z_1clQqsR6XMKUsaquGZRV6Eq_JJhY',
    appId: '1:295791005487:web:6a550067901b187b6a1bda',
    messagingSenderId: '295791005487',
    projectId: 'sample-firebase-ai-app-456c6',
    authDomain: 'sample-firebase-ai-app-456c6.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-456c6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_w6TvSkLm0qDNQmfhhmBBSpme6Md8UCs',
    appId: '1:295791005487:android:7ca6fd9cee014be86a1bda',
    messagingSenderId: '295791005487',
    projectId: 'sample-firebase-ai-app-456c6',
    storageBucket: 'sample-firebase-ai-app-456c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOD5voM-8YG7RTXNTM5v_-KGqNd21WyjI',
    appId: '1:295791005487:ios:d4cf71f8ee05688c6a1bda',
    messagingSenderId: '295791005487',
    projectId: 'sample-firebase-ai-app-456c6',
    storageBucket: 'sample-firebase-ai-app-456c6.firebasestorage.app',
    iosBundleId: 'com.example.alMehdiOnlineSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOD5voM-8YG7RTXNTM5v_-KGqNd21WyjI',
    appId: '1:295791005487:ios:d4cf71f8ee05688c6a1bda',
    messagingSenderId: '295791005487',
    projectId: 'sample-firebase-ai-app-456c6',
    storageBucket: 'sample-firebase-ai-app-456c6.firebasestorage.app',
    iosBundleId: 'com.example.alMehdiOnlineSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy5z_1clQqsR6XMKUsaquGZRV6Eq_JJhY',
    appId: '1:295791005487:web:b3a387429bdf77896a1bda',
    messagingSenderId: '295791005487',
    projectId: 'sample-firebase-ai-app-456c6',
    authDomain: 'sample-firebase-ai-app-456c6.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-456c6.firebasestorage.app',
  );
}
